name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ICYBIS_BUILD_PRIVATE: github.com/TinkerTech-Addons/IcyBIS-Build
      ICYBIS_BUILD_TOKEN: ${{ secrets.ICYBIS_BUILD_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - run: git config --global url.https://$ICYBIS_BUILD_TOKEN@github.com/.insteadOf https://github.com/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/TinkerTech-Addons/IcyBIS-Build.git
      - name: gather data
        run: |
          icybis package
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "IcyBIS.zip"

      - name: WoW Packager
        uses: BigWigsMods/packager@v2.3.1
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.ICYBIS_BUILD_TOKEN }}
