name: Release IcyBIS AddOn

on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  GITHUB_OAUTH: ${{ secrets.ICYBIS_BUILD_TOKEN }}

jobs:
  standalone_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@v2
